Repository CircuitDev192/Game3, pull requests merged in 2020-04, with the labels that each got.

#23 Weapon Sound Origin Change
  Assets/Prefabs/Weapons/SA_Wep_AssaultRifle01.prefab
  Assets/Prefabs/Weapons/SA_Wep_DesertEagle.prefab
  Assets/Prefabs/Weapons/SA_Wep_SpazShotgun.prefab
Labels: bug

#26 Issue25 automatic reloads
  Assets/Scripts/WeaponAnimScripts/WeaponStates/WeaponFireState.cs
Labels: bug

#45 Randomized Zombie Pitches
  Assets/Prefabs/Zombies/SA_Zombie_AirportSecurity.prefab
  Assets/Prefabs/Zombies/SA_Zombie_AirportWorker.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Bellhop.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Businessman.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Cheerleader.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Farmer.prefab
  Assets/Prefabs/Zombies/SA_Zombie_FarmersDaughter.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Firefighter.prefab
  Assets/Prefabs/Zombies/SA_Zombie_FootballPlayer.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Hobo.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Industrial.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Mechanic.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Mountie.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Pilot.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Pimp.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Prisoner.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Prostitute.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Roadworker.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Robber.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Runner.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Shopkeeper.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Soldier.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Streetman.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Tourist.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Trucker.prefab
  Assets/Scripts/ZombieScripts/Zombie States/ZombieContext.cs
Labels: enhancement

#51 Fix of buffered jump and backwards sprinting bugs
  Assets/Scripts/FirstPersonMovement.cs
  Assets/Scripts/PlayerAnimScripts/PlayerStates/PlayerAnimRun.cs
  Assets/Scripts/PlayerAnimScripts/PlayerStates/PlayerAnimWalk.cs
Labels: bug

#86 Weapon Range and Pickup Collider Fix
  Assets/Prefabs/Weapons/Pickups/Consumables/SA_Item_Ammo_AssaultRifle_Pickup_Box.prefab
  Assets/Prefabs/Weapons/Pickups/Consumables/SA_Item_Ammo_AssaultRifle_Pickup_Magazine.prefab
  Assets/Prefabs/Weapons/Pickups/Consumables/SA_Item_Ammo_Handgun_Pickup.prefab
  Assets/Prefabs/Weapons/Pickups/Consumables/SA_Item_Ammo_Handgun_Pickup_Magazine.prefab
  Assets/Prefabs/Weapons/Pickups/Consumables/SA_Item_Ammo_Shotgun_Pickup_Box.prefab
  Assets/Prefabs/Weapons/Pickups/Consumables/SA_Item_MedicBag_Pickup.prefab
  Assets/Prefabs/Weapons/Pickups/Consumables/SA_Wep_Flaregun_Ammo_Pckup.prefab
  Assets/Prefabs/Weapons/Pickups/Consumables/SA_Wep_FlashBang_Ammo_Pickup.prefab
  Assets/Prefabs/Weapons/Pickups/Consumables/SA_Wep_FragGrenade_Ammo_Pickup.prefab
  Assets/Prefabs/Weapons/Pickups/Consumables/SA_Wep_Suppressor_Pickup.prefab
  Assets/Prefabs/Weapons/SA_Wep_AssaultRifle01.prefab
  Assets/Prefabs/Weapons/SA_Wep_AssaultRifle02.prefab
  Assets/Prefabs/Weapons/SA_Wep_DesertEagle.prefab
  Assets/Prefabs/Weapons/SA_Wep_Katana.prefab
  Assets/Prefabs/Weapons/SA_Wep_Pistol.prefab
Labels: bug, enhancement

#90 Issue64 weather manager
  Assets/Prefabs/UI/GameUI.prefab
  Assets/Prefabs/Weapons/WeaponComponents/Flashlight Light.prefab
  Assets/Scripts/Management/WeatherManager.cs
  Assets/Scripts/Management/WeatherManager.cs.meta
  Assets/Scripts/RainEffectsController.cs
  Assets/Scripts/RainEffectsController.cs.meta
  Assets/Shaders/OceanShader.shadergraph
  Assets/Shaders/OceanShader.shadergraph.meta
  Assets/Shaders/PuddleSplash.shadergraph
  Assets/Shaders/PuddleSplash.shadergraph.meta
  Assets/VFX/Rain Splash.vfx
  Assets/VFX/Rain.vfx
Labels: Hella Nice

#98 Resolved issues 76, 84, and 27
  Assets/Scripts/FirstPersonMovement.cs
  Assets/Scripts/WeaponAnimScripts/WeaponStates/WeaponFireState.cs
  Assets/Scripts/WeaponAnimScripts/WeaponStates/WeaponIdleState.cs
  Assets/Scripts/WeaponAnimScripts/WeaponStates/WeaponSwapState.cs
Labels: bug

#126 Added main menu
  Assets/Scenes/Main Menu.unity
  Assets/Scripts/UI/UIMainMenuController.cs
  Assets/Scripts/UI/UIMainMenuController.cs.meta
Labels: Hella Nice, enhancement

#130 Fixed where consumables now show correct ammo count
  Assets/Scripts/Management/PlayerManager.cs
Labels: bug

#134 Number Keys and Ammo Pickup Fix
  .gitignore
  Assets/Scripts/UI/UIPlayerInfoController.cs
  Assets/Scripts/WeaponAnimScripts/WeaponStates/WeaponIdleState.cs
Labels: bug, enhancement

#140 Weapon / Zombie Balance
  Assets/Prefabs/Weapons/SA_Wep_AssaultRifle01.prefab
  Assets/Prefabs/Weapons/SA_Wep_AssaultRifle02.prefab
  Assets/Prefabs/Weapons/SA_Wep_DesertEagle.prefab
  Assets/Prefabs/Weapons/SA_Wep_Katana.prefab
  Assets/Prefabs/Weapons/SA_Wep_Pistol.prefab
  Assets/Prefabs/Zombies/SA_Zombie_AirportSecurity.prefab
  Assets/Prefabs/Zombies/SA_Zombie_AirportWorker.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Bellhop.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Businessman.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Cheerleader.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Farmer.prefab
  Assets/Prefabs/Zombies/SA_Zombie_FarmersDaughter.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Firefighter.prefab
  Assets/Prefabs/Zombies/SA_Zombie_FootballPlayer.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Hobo.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Industrial.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Mechanic.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Mountie.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Pilot.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Pimp.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Prisoner.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Prostitute.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Roadworker.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Robber.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Runner.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Shopkeeper.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Soldier.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Streetman.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Tourist.prefab
  Assets/Prefabs/Zombies/SA_Zombie_Trucker.prefab
  Assets/Scripts/Weapons/Throwables/Flashbang.cs
  Assets/Scripts/Weapons/Throwables/FragGrenade.cs
  Assets/Scripts/Weapons/Throwables/Rock.cs
  Assets/Scripts/ZombieScripts/Zombie States/ZombieContext.cs
  Assets/Scripts/ZombieScripts/Zombie States/ZombieFleeState.cs
  Assets/Scripts/ZombieScripts/Zombie States/ZombieInvestigateState.cs
Labels: bug, enhancement

#167 Final push
  Assets/Prefabs/Missions/Mission4.prefab
  Assets/Scripts/Missions/MissionFetch.cs
  Assets/Scripts/Missions/MissionKill.cs
  Assets/Scripts/Missions/MissionSurvive.cs
  Assets/Scripts/Missions/StartCollider.cs
  Assets/Scripts/Missions/ZombieAreaToClear.cs
  Assets/Scripts/UI/UIMissionInfoController.cs
Labels: Lit AF
